### ISSUE TITLE
Discrepancy between windows and percentage

### ISSUE THREAD

**Issue by JoeIzzard** [kas/percentage#10]
So it appears that percentage doesn't match what Windows is reporting at times. 

For example, currently, Windows is reporting 98% charged when I hover over the battery icon, but Percentage is reporting 97%. I know it's not much there but it does make me wonder about lower levels.

I will update this issue as I check at different levels throughout the week.

**System**

MacBook Pro Retina (Mid 2014)
Windows 10 Pro running in Bootcamp

**Comment by georgepauna** [comment]
I'm pretty sure the windows percent is updating less often that this program, so in fact the correct one is what you're seeing in "percentage.exe". I looked in the code, and it's textbook reading of battery status.

**Comment by JoeIzzard** [comment]
I have had my system just sitting plugged into my desk set up (Monitors and Power ect) and it has been sitting at that difference for about an hour so I don't think it's to do with the refresh rate. It may be a case of Windows not correctly reading the value or doing the math slightly differently.

**Comment by georgepauna** [comment]
then yes, it probably because the value 0.513 for example is computed in "percentage" as 51, using casting to int after multiplying by 100, while windows might be just rounding up, making it 52. This could be changed, but I don't think the project is maintained anymore. Maybe I'll branch it and continue work on it (I already have some changes, mentioned in the issue before this one)

**Comment by JoeIzzard** [comment]
That makes sense. I think if it is just a difference in rounding like that I wouldn't be too concerned. I was more concerned to see if the difference got worse at difference charge levels. Your changes do look interesting, would be good to see a fork just for those.

**Comment by kas** [comment]
Yes the percentage comes straight from SystemInformation.PowerStatus.BatteryLifePercent. Feel free to reopen if there's a better way to get the percentage.

Also georgepauna feel free to share your fork here, thanks
