### ISSUE TITLE
Able to remove the black background and make it transparent, and able to adjust the size

### ISSUE THREAD

**Issue by armaninyow** [kas/percentage#12]
I like this application, no need to hover over the battery icon.

**Comment by Elia0107** [comment]
Hi, how did you make trasparent background? can you share it? thanks

**Comment by ArmaninyowPH** [comment]
> Hi, how did you make trasparent background? can you share it? thanks

I'm sorry if you misunderstood my comment. It was just a suggestion.

**Comment by kas** [comment]
Transparent background added in latest release 1.2.0, thanks
