### ISSUE TITLE
Unable to set transparent backgroud, Sharper percentage text

### ISSUE THREAD

**Issue by Darkanalyser** [kas/percentage#17]
I am still having issues with non transparent background.
![image](https://user-images.githubusercontent.com/42247981/75714617-10af8200-5cf2-11ea-82e2-2515600d12c5.png)

Also, The text seems really blurred on higher resolutions.

**Comment by kas** [comment]
1.2.0 has a transparent background and I bumped the font size, can you see if it helps? Reopen if there are still issues
