### ISSUE TITLE
Digits looks blurry

### ISSUE THREAD

**Issue by ghost** [kas/percentage#2]
I have been searching for such a program for a long time, thank you for your work. The only thing I would like to correct is the blurry digits. Perhaps it is worth to increase the font thickness or its sharpness to bring it closer to other fonts in the task bar. Probably can't be said that they are completely blurred, but they don't look exactly as they would like.

**Comment by kas** [comment]
Hi Vladimir:

Thank you for creating this issue. I understand that the digits have a blurry look and I am not sure how to correct this. As it stands, the font family is the default Windows 10 font, Segoe UI, with a font size of 14. The current battery percentage is drawn with that font on a small image, and the image is shown in the system tray.

During development I experimented with other font families and sizes but they seemed to look just as blurry or even more blurry than what it looks like now.

I would be more than happy to merge a pull request that offers a fix for this issue.

**Comment by joshuali925** [comment]
It looks better if you check "override high DPI scaling behavior" under right click - properties - Compatibility. At least for me.

**Comment by jordiid96** [comment]
I've created a pull request to fix the issue.

**Comment by kas** [comment]
I took a hiatus from the project. With 1.2.0 I increased the font size which should help the issue, feel free to reopen if there are other suggestions on how to prevent blurriness
