### ISSUE TITLE
请把电量数字加粗

### ISSUE THREAD

**Issue by mr-zhang-shsf** [kas/percentage#22]
现在的电量数字字体小且细，不容易分辨，请使用和时间数字一样的字体，谢谢！
Now the power digital font is small and thin, not easy to distinguish, please use the same font as the time number, thank you!

**Comment by kas** [comment]
Font size increased in 1.2.0, which should help with the thin issue. Segoe UI is the font used by the icon, same font as Windows 10 taskbar time/date
