### ISSUE TITLE
I made some nice improvements and want to commit

### ISSUE THREAD

**Issue by georgepauna** [kas/percentage#9]
Based on your project, I changed the font to a bitmap one, with digital digits, made the background transparent and added an animation when charging. Let me know if you want to include those changes
![digital](https://user-images.githubusercontent.com/42321881/44081666-f1a187f8-9fb7-11e8-94d8-96a4f914c2a8.PNG)

**Comment by m4rii0** [comment]
It looks great!

Can you please share the code?

Thank you

**Comment by wocala** [comment]
> Based on your project, I changed the font to a bitmap one, with digital digits, made the background transparent and added an animation when charging. Let me know if you want to include those changes
> ![digital](https://user-images.githubusercontent.com/42321881/44081666-f1a187f8-9fb7-11e8-94d8-96a4f914c2a8.PNG)

Great Work.
May I know how to get your version?
Thanks a lot!!

**Comment by Gongzq5** [comment]
Could you please share your code?
Thank you very much !!!

**Comment by kas** [comment]
Hey georgepauna, thanks for sharing. Can you share the fork?

Some of these features might be too complicated IMO for how I prefer the project to look, but folks in the thread would appreciate your fork.
